seed: 42

data:
  root:        "H:/KhoaLuan/data/xBD"
  img_size:    512
  val_split:   0.15
  num_workers: 0

model:
  encoder:         "scalemae"
  encoder_weights: "imagenet"

loss:
  w_loc:       0.4
  w_dmg:       0.6
  focal_gamma: 2.0

training:
  epochs:       50
  batch_size:   8
  lr:           0.00005
  weight_decay: 0.0001
  save_every:   5

experiment:
  name: "scalemae_vit"
  dir:  "experiments/scalemae_vit"